// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1763217054);
user_pref("app.update.lastUpdateTime.background-update-timer", 1763217054);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1763217054);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1763217054);
user_pref("basebrowser.migration.version", 6);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 155);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.search.totalSearches", 1);
user_pref("browser.security_level.noscript_inited", true);
user_pref("browser.security_level.security_custom", false);
user_pref("browser.security_level.security_slider", 4);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20251110091947");
user_pref("browser.startup.homepage_override.mstone", "140.5.0");
user_pref("browser.startup.homepage_override.torbrowser.version", "15.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1763217769);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"vertical-spacer\",\"urlbar-container\",\"security-level-button\",\"new-identity-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"_73a6fe31-595d-460b-a920-fcc0f8843232_-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"_73a6fe31-595d-460b-a920-fcc0f8843232_-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"unified-extensions-area\",\"vertical-tabs\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":22,\"currentVersionBaseBrowser\":2,\"currentVersionTorBrowser\":1,\"newElementCount\":0}");
user_pref("browser.urlbar.placeholderName.private", "DuckDuckGo");
user_pref("captchadetection.lastSubmission", 1763217);
user_pref("distribution.iniFile.exists.appversion", "140.5.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("dom.security.https_only_mode_ever_enabled_pbm", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.lastAppBuildId", "20251110091947");
user_pref("extensions.lastAppVersion", "140.5.0");
user_pref("extensions.lastPlatformVersion", "140.5.0");
user_pref("extensions.lastTorBrowserVersion", "15.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.torbutton.launch_warning", false);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{73a6fe31-595d-460b-a920-fcc0f8843232}", true);
user_pref("extensions.webextensions.uuids", "{\"{73a6fe31-595d-460b-a920-fcc0f8843232}\":\"2316d15b-18d5-4a4c-b0bc-b8eee89c32cf\",\"default-theme@mozilla.org\":\"f409fe89-d37e-4f2f-ad0a-b9b3780a247d\",\"uBlock0@raymondhill.net\":\"dc86625b-71c9-470c-8049-aad1ae910130\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1763218152);
user_pref("intl.accept_languages", "en-US, en");
user_pref("javascript.use_us_english_locale", true);
user_pref("media.gmp-manager.buildID", "20251110091947");
user_pref("media.gmp-manager.lastCheck", 1763217054);
user_pref("media.gmp-manager.lastEmptyCheck", 1763217054);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.proxy.socks_port", 9050);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1763218152);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.globalprivacycontrol.was_ever_enabled", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.resistFingerprinting.letterboxing.didForceSize", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("spellchecker.dictionary", "en_US");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1763218152);
user_pref("toolkit.startup.last_success", 1763217767);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("torbrowser.migration.version", 9);
